name: rexios_lints_example
description: An example project that uses rexios_lints
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0

dev_dependencies:
  rexios_lints:
    path: ../

dependency_overrides:
  meta: ^1.18.0
