name: rexios_lints
description: A collection of the linting rules I use for Flutter/Dart projects and packages
version: 16.0.0
homepage: https://github.com/Rexios80/rexios_lints

environment:
  sdk: ^3.10.0

dependencies:
  lints: ^6.0.0
  flutter_lints: ^6.0.0
  analyzer: ^8.0.0
  analyzer_plugin: ^0.13.7
  analysis_server_plugin: ^0.2.1
  source_gen: ^4.0.2
  collection: ^1.19.1

dev_dependencies:
  test: ^1.26.2
  http: ^1.2.1
  pub_semver: ^2.1.4
  analyzer_testing: ^0.1.2
