name: rexios_lints
description: A collection of the linting rules I use for Flutter/Dart projects and packages
#! MAKE SURE TO REGENERATE THE RULES AFTER UPDATING THE MAJOR VERSION
version: 17.0.3
homepage: https://github.com/Rexios80/rexios_lints

environment:
  sdk: ^3.10.0

dependencies:
  lints: ^6.0.0
  flutter_lints: ^6.0.0
  analyzer: ^10.0.2
  analyzer_plugin: ^0.14.0
  analysis_server_plugin: ^0.3.3
  source_gen: ^4.0.2
  collection: ^1.19.1
  meta: ^1.17.0

dev_dependencies:
  test: ^1.26.2
  http: ^1.2.1
  pub_semver: ^2.1.4
  analyzer_testing: ^0.1.10
  test_reflective_loader: ^0.4.0
  path: ^1.9.1
